// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzygevgeeuhtdkjdhhoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eWdldmdlZXVodGRramRoaG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzE3MjgsImV4cCI6MjA3NDYwNzcyOH0.1nCyPBwghMKv-9NZBFqTVOguJyVEo6vjbBN6Pp3nGUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});